version: "3"

services:
  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mongo:
    container_name: terasys-mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/data/db
    environment:
      - MONGO_DATA_DIR=data/db

  api:
    container_name: terasys-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - ./api:/code
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - VIRTUAL_HOST=api.terasys.com
      - VIRTUAL_PORT=3000

volumes:
  db_data:
